apiVersion: apps/v1
kind: Deployment
metadata:
  name: viktor-guestbook-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viktor-guestbook-backend
  template:
    metadata:
      labels:
        app: viktor-guestbook-backend
    spec:
      containers:
        - name: viktor-guestbook-backend
          image: ghcr.io/thesuperswan/guestbook-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-viktor
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-viktor
                  key: POSTGRESQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-viktor
                  key: POSTGRESQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-viktor
                  key: POSTGRESQL_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: viktor-guestbook-backend
spec:
  selector:
    app: viktor-guestbook-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080

